spring:
  application:
    name: HRManagementSystem

  jackson:
    date-format: dd.MM.yyyy HH:mm
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8081
  info:
    title: Ticketing System API
    version: 1.0
    description: Bu HR ucun bir sistemdir. Muraciet eden namizedleri elave eden kicik bir programdir....
    contact:
      name: Arzu Ahmedova
      email: arzuahmedova.1707@gmail.com

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html



jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token:
    expiration: 300000  # 5 minutes in milliseconds
  refresh-token:
    expiration: 3600000  # 1 hour in milliseconds


